### ISSUE TITLE
Python 3.5+ Supports Async

### ISSUE THREAD

**Issue by stopspazzing** [lixxu/sanic-jinja2#10]
https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-492

As long as the version of python is 3.5 or higher, async is included in the code. Please revert your code. 😄 

Version python 3.5+ is required to run Sanic, therefore by default async should be used.

**Comment by lixxu** [comment]
for jinja2, python3.6+ is required for async.

**Comment by stopspazzing** [comment]
Ah... I see it now in docs: 

```
enable_async If set to true this enables async template execution which
allows you to take advantage of newer Python features. This requires Python 3.6 or later.
```
