### ISSUE TITLE
Custom the path of template folder

### ISSUE THREAD

**Issue by JoshYuJump** [lixxu/sanic-jinja2#14]
My templates not in the  `app/templates`, but `app/cms/templates`.
So I import the `PackageLoader` from the `jinja2`.
Would you support to custom the path?

```python

from jinja2 import PackageLoader
from sanic_jinja2 import SanicJinja2

# Jinja2 template engine
template_package_loader = PackageLoader(app.name, 'cms/templates')
template = SanicJinja2(app, loader=template_package_loader)
```

**Comment by lixxu** [comment]
supported, update to `0.5.5` and pass `pkg_path='cms/templates'` to customize it.
