### ISSUE TITLE
update_request_context is gone

### ISSUE THREAD

**Issue by espositofulvio** [lixxu/sanic-jinja2#21]
In a recent update I see update_request_context() is not a member of SanicJinja2 class anymore but I really can't figure out how to use the context_processors parameter to update the context. My understanding is that that param is appended to the request_middlewares of the app, but I can't see how to update the context in a middleware as the context isn't accessible there. Any help?

**Comment by lixxu** [comment]
last merge moves the methods out, do you want to use it as class methods? I'll make a link to it if you want it back.

**Comment by xen** [comment]
You can still use Sanic middlewares. Can you provide an example of code what do you want to achieve?

**Comment by espositofulvio** [comment]
Hi,
I just want to know how I can add an object to the context every time (I'm injecting the user object in the template).
The way I'm doing it now is deriving a class from SanicJinja2:

```python
class TemplateEnging( SanicJinja2 ):
  def update_request_context( self, request, context ):
    super().update_request_context( request, context )
    user = get_logged_in_user( request )
    if user:
      context.setdefault( 'user', user )
```
In my template, the menu shows an admin section only if the user.is_in_group( 'admin' ) is True.
{% if user.is_in_group( 'admin' ) %}

{% endif %}

**Comment by xen** [comment]
Does this approach fit your needs?:

```py

@app.middleware('request')
async def add_user_to_request(request):
    user = get_logged_in_user(request)
    if user:
        request['user'] = user
```

Put it somewhere in your main module after initialization of the sanic itself. 

Then in template access it:

```
{% if request.get('user') and request.get['user'].is_in_group('admin') %}

{% endif %}
```

**Comment by espositofulvio** [comment]
While I can certainly use your workaround, having a way to inject data in the template context is something I would like to have anyway. In my case, it clearly provides for nicer syntax in the template, but I guess that might be other use cases.

**Comment by xen** [comment]
It probably me just made it this ugly, you can follow your style. I just want to point that Sanic already has an infrastructure for such needs. So, I'm not sure that this library should support another point of extensibility.

Anyway if you find other cases don't hesitate to mention me.

**Comment by lixxu** [comment]
I moved it to the class back.

**Comment by espositofulvio** [comment]
@lixxu I don't think the way you fixed it is actually working. As all the render* methods are calling the plain function, redefining update_request_context in a derived class has no effect, as the member function is never actually called.
