### ISSUE TITLE
sanic.exceptions.URLBuildError: Endpoint with name `/static` was not found

### ISSUE THREAD

**Issue by kobelover** [lixxu/sanic-jinja2#25]
hi,
as we know, For jinja2 at flask, import CSS files into HTML looks like that:
```
{{ url_for('/static', filename='script/jquery.min.js') }}
```
but get wrong at sanic-jinja2
```
Error: Endpoint with name `/static` was not found
```

**Comment by gabrii** [comment]
It looks like you haven't defined the static directory in your app:
app.static('/static', DIRECTORY_IN_ABSOLUTE_PATH)

Close this issue in case this solves it.

**Comment by kobelover** [comment]
thanks gabrii @gabrii
