### ISSUE TITLE
Usage in other files/modules

### ISSUE THREAD

**Issue by iSevenDays** [lixxu/sanic-jinja2#3]
Hello

Where do you suggest to store

`jinja = SanicJinja2(app)`

so it can be used in other modules/blueprints?

I would like to have something like

`existent_jinja = sanic.jinja`

**Comment by lixxu** [comment]
it can be accessed via `app.extensions['jinja2']`, and you can also import it in other files

**Comment by iSevenDays** [comment]
@lixxu thank you!
