### ISSUE TITLE
issue with sanic 20.3.0: Request is not iterable

### ISSUE THREAD

**Issue by xnuinside** [lixxu/sanic-jinja2#35]
@lixxu, hi! first of all thanks for very useful addon. 
I met an issue with Sanic 20.3.0 version. On 19.x.x all works well.
<img width="399" alt="Screen Shot 2020-05-16 at 11 09 43 PM" src="https://user-images.githubusercontent.com/15959809/82129397-24379880-97cb-11ea-8542-93af4ff3364c.png">
<img width="803" alt="Screen Shot 2020-05-16 at 11 09 19 PM" src="https://user-images.githubusercontent.com/15959809/82129399-27cb1f80-97cb-11ea-991e-935deb40253c.png">

**Comment by lixxu** [comment]
Because `20.X` removes the `__contains__` method. Please try new version of `sanic-jinja2` on pypi.
![image](https://user-images.githubusercontent.com/264487/82142110-96ac8500-986c-11ea-82a6-5eef83817f3f.png)

**Comment by xnuinside** [comment]
@lixxu thank you!
