### ISSUE TITLE
TypeError: 'Request' object is not subscriptable when using flash function

### ISSUE THREAD

**Issue by Eslih** [lixxu/sanic-jinja2#38]
Hi,

It seems like there is a bug when using Sanic version 20.12.1 (the latest version at this moment).

Everything works fine as long I am not using the flash messages functionality. As soon as I use this, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sanic/app.py", line 914, in handle_request
    response = await response
  File "/usr/local/lib/python3.9/site-packages/sanic_jinja2/__init__.py", line 181, in wrapped
    context = yield from coro(*args, **kwargs)
  File "/frontend/frontend/blueprints/users.py", line 14, in foo
    request['flash']('success message', 'success')
TypeError: 'Request' object is not subscriptable
```

**Comment by lixxu** [comment]
you need use `request.ctx` for custom data (see [https://github.com/sanic-org/sanic/commit/c54a8b10bb848833defe366400079db1f09fa037](https://github.com/sanic-org/sanic/commit/c54a8b10bb848833defe366400079db1f09fa037).
So, you can try `request.ctx.flash('success message', 'success')`.

And, in new version `0.9.0`, you can use it like this (see readme or example for details, they'are all updated):
```
jinja_obj = SanicJinja2(app, ...)
...
jinja_obj.flash(request, "message", "category")
```
