### ISSUE TITLE
i18n example

### ISSUE THREAD

**Issue by mikmatko** [lixxu/sanic-jinja2#4]
Hello,

This may be more related to how Jinja2 works in general but I couldn't figure out. What would be the best approach to using i18n with Sanic? For now I'm just creating multiple `SanicJinja2` instances with different translations installed. E.g.

```python
locale_dir = "locale"
translations_fi = Translations.load(locale_dir, 'fi')
translations_en = Translations.load(locale_dir, 'en')
JINJA_FI = SanicJinja2(app, extensions=['jinja2.ext.i18n'])
JINJA_EN = SanicJinja2(app, extensions=['jinja2.ext.i18n'])
JINJA_FI.env.install_gettext_translations(translations_fi)
JINJA_EN.env.install_gettext_translations(translations_en)
```

And then I use which ever matches the locale (which I'm determining elsewhere). This seems a bit silly approach. Do you have any suggestions how to approach this better?

Thanks!

**Comment by lixxu** [comment]
I'm working on an extension `sanic-babel` (inspired from `flask-babel`), but no due date to release as `sanic` still has some differences with `flask`

**Comment by lixxu** [comment]
this [sanic-babel](https://github.com/lixxu/sanic-babel) may be helpful.

**Comment by lixxu** [comment]
long time no response.
