### ISSUE TITLE
error occur when init sanic-jinja2:' ModuleNotFoundError: No module named '

### ISSUE THREAD

**Issue by gamexy** [lixxu/sanic-jinja2#40]
there is my code :
from sanic import Sanic
from sanic import response
from sanic.response import text
from sanic.response import json
from sanic_jinja2 import SanicJinja2

app = Sanic("MyApp")
jinja = SanicJinja2()
jinja.init_app(app)

and this is result:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 343, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'MyApp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 12, in <module>
    jinja.init_app(app)
  File "/usr/local/lib/python3.6/site-packages/sanic_jinja2/__init__.py", line 120, in init_app
    pkg_name or app.name, pkg_path or "templates"
  File "/root/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 237, in __init__
    provider = get_provider(package_name)
  File "/root/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 345, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'MyApp'

**Comment by lixxu** [comment]
I think you need name the folder to `MyApp`.

**Comment by lc-thomas** [comment]
you need to add a folder in between, that's weird but meh...

So :
**./server.py**
``` python
from sanic import Sanic
from sanic.response import json
from sanic_jinja2 import SanicJinja2

app = Sanic(name='MyWebserver')
jinja = SanicJinja2(app, pkg_name="pkg")
```

and place your templates in :
**./pkg/templates/**

**Comment by timanttikuutio** [comment]
> you need to add a folder in between, that's weird but meh...
> 
> So :
> **./server.py**
> 
> ```python
> from sanic import Sanic
> from sanic.response import json
> from sanic_jinja2 import SanicJinja2
> 
> app = Sanic(name='MyWebserver')
> jinja = SanicJinja2(app, pkg_name="pkg")
> ```
> 
> and place your templates in :
> **./pkg/templates/**

I am the friend of CrypticzXI(the OP of the the other open issues with similar issue) and i just tried running my api on a new vps with python and all the packages just installed. it didn't work(same error as shown on this post) but once i did what you suggested it started working. This must be some kind of a bug with the library itself and i think @lixxu should probably look into it. The same api is working fine on my PC and on another vps and both have the same versions of each of the packages installed

**Comment by lixxu** [comment]
please check jinja 3.0 changelog [(https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader)](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader)
![image](https://user-images.githubusercontent.com/264487/123345333-6a435c00-d588-11eb-8554-270f769b9f41.png)

**Comment by lixxu** [comment]
close as long time no update.
