### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by ghost** [lixxu/sanic-jinja2#42]
Hello. I updated your library today, and I get an error when I run it: `ValueError: __main__.__spec__ is None` at `jinja = SanicJinja2(app)`.
Installed libraries:
- `Jinja2==3.0.0`
- `sanic==21.3.4`
- `sanic-jinja2==0.10.0`

Code:
```python
from sanic import Sanic

app = Sanic(__name__)
jinja = SanicJinja2(app)


@app.route('/', methods=['GET', 'POST'])
async def index(request):
	return jinja.render('index.html', request)


if __name__ == '__main__':
	app.run(debug=True)
```

**Comment by lixxu** [comment]
Could you please provide more error details? I can not locate the error.

**Comment by ghost** [comment]
`Traceback (most recent call last):
  File "/root/j/main.py", line 4, in <module>
    jinja = SanicJinja2(app)
  File "/root/.local/lib/python3.9/site-packages/sanic_jinja2/__init__.py", line 95, in __init__
    self.init_app(app, loader, pkg_name or app.name, pkg_path)
  File "/root/.local/lib/python3.9/site-packages/sanic_jinja2/__init__.py", line 119, in init_app
    loader = PackageLoader(
  File "/root/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 286, in __init__
    spec = importlib.util.find_spec(package_name)
  File "/usr/local/lib/python3.9/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: __main__.__spec__ is None`

**Comment by lixxu** [comment]
The error is from `Jinja2 3.0.0` [Use PEP 451 API to load templates with PackageLoader. #1168](https://jinja.palletsprojects.com/en/3.0.x/changes/#version-3-0-0). 
This can explain: [https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader)
