### ISSUE TITLE
Jinja erroring out

### ISSUE THREAD

**Issue by CrypticzXI** [lixxu/sanic-jinja2#43]
It seems just to be me as m friend tried the script and it worked perfectly fine,

**Here is the code**
`from sanic import Sanic
from sanic_session import Session, InMemorySessionInterface
from sanic_jinja2 import SanicJinja2

app = Sanic(__name__)

session = Session(app, interface=InMemorySessionInterface())
jinja = SanicJinja2(app, session=session)

@app.route('/')
@jinja.template('index.html')  # decorator method is staticmethod
async def index(request):
    jinja.flash(request, 'success message', 'success')
    jinja.flash(request, 'info message', 'info')
    jinja.flash(request, 'warning message', 'warning')
    jinja.flash(request, 'error message', 'error')
    jinja.session(request)["session key"] = "session value"
    return {'greetings': 'Hello, sanic!'}

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=True)`
    
**Here is the error**
`Traceback (most recent call last):
  File "C:\Path\", line 11, in <module>
    jinja = SanicJinja2(app, session=session)
  File "C:\Path\Python\Python38\lib\site-packages\sanic_jinja2\__init__.py", line 95, in __init__
    self.init_app(app, loader, pkg_name or app.name, pkg_path)
  File "C:\Path\Python\Python38\lib\site-packages\sanic_jinja2\__init__.py", line 119, in init_app
    loader = PackageLoader(
  File "C:\Path\Python\Python38\lib\site-packages\jinja2\loaders.py", line 286, in __init__
    spec = importlib.util.find_spec(package_name)
  File "C:\Path\Python\Python38\lib\importlib\util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: __main__.__spec__ is None`

**Comment by lixxu** [comment]
please check this: [https://github.com/lixxu/sanic-jinja2/issues/42#issuecomment-841746905](https://github.com/lixxu/sanic-jinja2/issues/42#issuecomment-841746905)

**Comment by CrypticzXI** [comment]
I tried using https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader
like this jinja = SanicJinja2(app, package_path="templates", encoding="utf-8") and the error was
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by lixxu** [comment]
If you want to use the parameter `encoding`, you need create a `PackageLoader` instance first, which accepts `encoding` parameter.
e.g.
```
loader = PackageLoader(..., package_path="templates", encoding="utf-8")
jinja = SanicJinja2(app, loader=loader)
```

**Comment by CrypticzXI** [comment]
what exactly is a package_name? Anything I think would work doesnt...

**Comment by lixxu** [comment]
please check this: [https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.PackageLoader)

**Comment by CrypticzXI** [comment]
ValueError: The 'main' package was not installed in a way that PackageLoader understands.

Yeah, I'm stuck now.

**Comment by lixxu** [comment]
The package here is like normal python package.

The following example looks up templates in the `pages` directory within the `project.ui` package.

`loader = PackageLoader("project.ui", "pages")`

**Comment by CrypticzXI** [comment]
I set it to "main" as that would be what it is and it's trying to run my main.py which starts my discord bot

**Comment by CrypticzXI** [comment]
What else could it be? my friend says its a issue with my computer

**Comment by CrypticzXI** [comment]
I installed a later version and updated it, i keep getting this: ValueError: The 'main' package was not installed in a way that PackageLoader understands.
My friend can run these same files I have.

**Comment by lixxu** [comment]
please try rename the file `main.py` to others.

**Comment by CrypticzXI** [comment]
My friend also as the name as main.py, it still continues to work for him.

**Comment by lixxu** [comment]
Do you have the same version of Jinja?

**Comment by CrypticzXI** [comment]
Yes, Latest

**Comment by lixxu** [comment]
Do you have the same folder/files structure?

**Comment by CrypticzXI** [comment]
As far as I am aware yes.

Test_Folder
    main.py
    templates

**Comment by lixxu** [comment]
what's the folder name contains main.py? change `jinja = SanicJinja2(app, session=session)` to `jinja = SanicJinja2(app, session=session, pkg_name=YOUR_FOLDER_NAME)`

**Comment by CrypticzXI** [comment]
AttributeError: type object 'FOLDER_NAME' has no attribute 'startswith'

**Comment by lixxu** [comment]
use the folder name contains main.py to replace FOLDER_NAME.

**Comment by CrypticzXI** [comment]
Yeah yeah, Well in this case the folder name is Sanic so the error is 
AttributeError: type object 'Sanic' has no attribute 'startswith'

**Comment by lixxu** [comment]
use another name for your codes folder.

**Comment by CrypticzXI** [comment]
ModuleNotFoundError: No module named 'Testing'

**Comment by lixxu** [comment]
e.g. the folder structure likes this:
```
hello\
    main.py
    templates
```
then `jinja = SanicJinja2(app, session=session, pkg_name="hello")`

**Comment by CrypticzXI** [comment]
Yes, My folders are like that

**Comment by lixxu** [comment]
if your folder likes this, the code should work.
![image](https://user-images.githubusercontent.com/264487/120595282-b103d180-c474-11eb-856a-eefc2db4503b.png)

![image](https://user-images.githubusercontent.com/264487/120595239-a21d1f00-c474-11eb-8fbc-dc38f6e3f884.png)

![image](https://user-images.githubusercontent.com/264487/120595408-e3153380-c474-11eb-8cca-adfe253a57bb.png)

**Comment by CrypticzXI** [comment]
Still that same error, ModuleNotFoundError: No module named 'Testing'

**Comment by lixxu** [comment]
can you provide the snapshot of your folder structure?

**Comment by CrypticzXI** [comment]
![image](https://user-images.githubusercontent.com/69183820/120596328-86e1ed80-c43b-11eb-8e50-4fdf8f5f246c.png)

**Comment by lixxu** [comment]
use `pkg_name = "Demo"` instead.

**Comment by CrypticzXI** [comment]
Yeah I was, still same error ModuleNotFoundError: No module named 'Demo'

**Comment by lixxu** [comment]
use console to run it, not in the IDE.

**Comment by CrypticzXI** [comment]
I'm trying both

**Comment by lixxu** [comment]
should be your environment problem. not sanic-jinja2 and jinja package. please check with your friends.

**Comment by CrypticzXI** [comment]
alright, Thanks for trying

**Comment by lonngxiang** [comment]
> I'm trying both

same issue, have you fixed it?

**Comment by lonngxiang** [comment]
> should be your environment problem. not sanic-jinja2 and jinja package. please check with your friends.

sanic                   21.6.2
sanic-jinja2            0.10.0
sanic-routing           0.7.1
