### ISSUE TITLE
AttributeError: 'Sanic' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by markmark1** [lixxu/sanic-jinja2#45]
jinja2-sanic-code.py", line 10, in <module>
    session = Session(app, interface=InMemorySessionInterface())
/lib/python3.9/site-packages/sanic_session/__init__.py", line 21, in __init__
    self.init_app(app, interface)
lib/python3.9/site-packages/sanic_session/__init__.py", line 25, in init_app
    if not hasattr(app.ctx, "extensions"):
AttributeError: 'Sanic' object has no attribute 'ctx'

on just running basic example from home page

**Comment by lixxu** [comment]
update sanic-session to latest version to try.
