### ISSUE TITLE
How to pass a variable globally to a template?

### ISSUE THREAD

**Issue by zhenzi0322** [lixxu/sanic-jinja2#48]
For example: after I logged in successfully, I need to hide the login button and show the login user's information

**Comment by lixxu** [comment]
you can refer to [https://sanicframework.org/en/guide/basics/middleware.html#attaching-middleware](https://sanicframework.org/en/guide/basics/middleware.html#attaching-middleware), then use `request.ctx.user` in template.

**Comment by lixxu** [comment]
closed as long time feedback.
