### ISSUE TITLE
Python 3.10 ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by mikekeda** [lixxu/sanic-jinja2#50]
I upgraded Python to 3.10 and got this error:
```
  File "sanic_jinja2/__init__.py", line 6, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

We need to replace this line https://github.com/lixxu/sanic-jinja2/blob/master/sanic_jinja2/__init__.py#L6 with
`from collections.abc import Mapping`

**Comment by lixxu** [comment]
updated, try new version please.

**Comment by mikekeda** [comment]
works, thanks
