### ISSUE TITLE
How to call a python function from template?

### ISSUE THREAD

**Issue by beliboba** [lixxu/sanic-jinja2#52]
In flask a could use @app.context_processor but what should i do in Sanic?
![image](https://user-images.githubusercontent.com/73661136/161979311-5246284a-fc79-4b72-86cf-d13d2d6880b4.png)

**Comment by lixxu** [comment]
there is a `add_env` method to add global function or filter to template.

```python

def add_env(self, name, obj, scope="globals"):
    if scope == "globals":
        self.env.globals[name] = obj
    elif scope == "filters":
        self.env.filters[name] = obj
```

**Comment by beliboba** [comment]
Where do i put it? And is there any examples?

**Comment by lixxu** [comment]
```python
jinja = SanicJinja2(app)
jinja.add_env("func_name", func)

```

**Comment by beliboba** [comment]
and how do i make it work with async functions?

**Comment by beliboba** [comment]
I get this error 
TypeError: 'str' object is not callable

**Comment by lixxu** [comment]
Could you paste your code?

**Comment by beliboba** [comment]
![image](https://user-images.githubusercontent.com/73661136/162609995-6034164e-fb95-47dd-afb6-9297e6747582.png)
![image](https://user-images.githubusercontent.com/73661136/162610005-a0d691b3-fa4c-4349-bb52-e6096b6a6d1d.png)
![image](https://user-images.githubusercontent.com/73661136/162610025-507f0e7c-4dd9-40b6-97b8-64b4eeac6414.png)

**Comment by lixxu** [comment]
`jinja.add_env("test", test)`

**Comment by beliboba** [comment]
Oh
Thank you🤗🤗
